In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

it is a process using domain knoledhe to extract feature from raw data. these feature can be used to improvew the performance of machine learning algorithm

# Standardization

In [42]:
df = pd.read_csv('Social_Network_Ads.csv')

In [43]:
print(df.shape)
print(df.columns)

(400, 3)
Index(['Age', 'EstimatedSalary', 'Purchased'], dtype='str')

In [36]:
df.sample(5)

     Age  EstimatedSalary  Purchased
17    45            26000          1
293   37            77000          0
46    25            79000          0
192   29            43000          0
312   38            50000          0

In [37]:
df = df.iloc[:,2:]

In [38]:
df.sample(5)

     Purchased
95           0
263          0
143          0
255          1
130          0

Train test split

In [44]:
from sklearn.model_selection import train_test_split

X = df.drop('Purchased', axis=1)
y = df['Purchased']
X_train, X_test, y_train, y_test = train_test_split(X,y,
test_size=0.3,
random_state=0)
X_train.shape, X_test.shape

((280, 2), (120, 2))

StandardScaler

In [45]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

#fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)

#transform train and test sets
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [47]:
scaler.mean_

array([3.78642857e+01, 6.98071429e+04])

In [49]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

In [50]:
np.round(X_train.describe(),1)

         Age  EstimatedSalary
count  280.0            280.0
mean    37.9          69807.1
std     10.2          34641.2
min     18.0          15000.0
25%     30.0          43000.0
50%     37.0          70500.0
75%     46.0          88000.0
max     60.0         150000.0

In [51]:
np.round(X_train_scaled.describe(),1)

         Age  EstimatedSalary
count  280.0            280.0
mean     0.0              0.0
std      1.0              1.0
min     -1.9             -1.6
25%     -0.8             -0.8
50%     -0.1              0.0
75%      0.8              0.5
max      2.2              2.3