In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

it is a process using domain knoledhe to extract feature from raw data. these feature can be used to improvew the performance of machine learning algorithm

# Standardization

In [6]:
df = pd.read_csv('Social_Network_Ads.csv')

In [7]:
df.sample(5)

     Age  EstimatedSalary  Purchased
370   60            46000          1
160   32           100000          1
356   54            70000          1
161   25            90000          0
339   39           122000          1

In [3]:
df = df.iloc[:,2:]

In [4]:
df.sample(5)

     Purchased
157          0
321          1
335          0
96           0
317          0

Train test split

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('Purchased',axis=1),
df['Purchased'],
test_size=0.3,
random_state=0)
X_train.shape, X_test.shape

((280, 2), (120, 2))

Standard scaler class

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

#fit the to the train set, it will learn the parameter
scaler.fit(X_train)

#transform train and test set
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
scaler.mean_

array([3.78642857e+01, 6.98071429e+04])